### PR TITLE
Omit private paths in populated Documents

### PR DESCRIPTION
**Pull request by StbX**
I'm not sure if this is the best way... But it works for me.

### CODE REVIEW

**Comment by yamadapc** [comment]
Hum... I think we can do this through the schema declaration, right? Just
looking at the `ref`s? I really want to add some tests to it, just so we can
see what causes the problem and be sure this works properly. Thanks for the
PR. I can't deal with this _now_, but I'll do my best to fix it by tomorrow.

I don't feel super about introducing another dependency, but I think it doesn't
matter much. Maybe we could use `object_path.has(obj, path)` instead of
`doc.$__ && doc.$__.populated` and statements like these. I'm surprised that
`.toJSON` doesn't get called on the populated paths.

**Comment by yamadapc** [comment]
I've implemented a version with tests, see if it works for you. It's released in `0.5.0`. Thanks :)

**Comment by yamadapc** [comment]
@StbX Let me know if it fixes the problem for you and what you think of the implementation.

**Comment by StbX** [comment]
Thank you for the fast patch. And sorry, I couldn't take a look on it. I will do it tomorrow.

**Pull request closed without merging**
